include_directories("${CMAKE_SOURCE_DIR}/${OUTPUT_ROOT_DIR}/include")

include("${CMAKE_CURRENT_LIST_DIR}/third_party/threads.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/third_party/duktape.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/third_party/spiffs.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/third_party/libevent.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/third_party/wolfssl.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/third_party/libtomcrypt.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/third_party/http_parser.cmake")
find_package(Threads REQUIRED)
if (NOT CMAKE_USE_PTHREADS_INIT)
    message(FATAL_ERROR "Failed to find Pthreads")
endif()
list(APPEND target_libs ${CMAKE_THREAD_LIBS_INIT})

